export const ADD_ARTICLE = "ADD_ARTICLE";
export const REMOVE_ARTICLE = "REMOVE_ARTICLE";
export const UPDATE = "UPDATE";

export const UPDATE_REST_TIME = "UPDATE_REST_MINUTE_TIME";
export const UPDATE_EXERCISE_TIME = "UPDATE_EXERCISE_MINUTE_TIME";
export const UPDATE_SETS_COUNT = "UPDATE_SETS_COUNT";
export const UPDATE_REPS_COUNT = "UPDATE_REPS_COUNT";
export const UPDATE_COMPLETE_STATUS = "UPDATE_COMPLETE_STATUS";
export const UPDATE_PENDING_STATUS = "UPDATE_PENDING_STATUS";
export const UPDATE_INACTIVE_STATUS = "UPDATE_INACTIVE_STATUS";
export const RESET_APPLICATION = "RESET_APPLICATION";

export enum STATUS {
    COMPLETE = "Complete",
    PENDING = "Pending",
    INACTIVE = "Inactive"
}
